FROM golang:1.24-bullseye AS builder

ARG PROTOC_VERSION=33.1
ARG PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
ARG PROTOC_DOWNLOAD=https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}

ARG PROTOC_GEN_GO_VERSION=v1.36.0

ENV PATH="/go/bin:${PATH}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    unzip wget ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN wget -qO /tmp/${PROTOC_ZIP} ${PROTOC_DOWNLOAD} \
 && unzip -o /tmp/${PROTOC_ZIP} -d /usr/local bin/protoc \
 && unzip -o /tmp/${PROTOC_ZIP} -d /usr/local include/* \
 && rm /tmp/${PROTOC_ZIP}

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@${PROTOC_GEN_GO_VERSION}
WORKDIR /app

ENTRYPOINT ["protoc"]
