// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: loadtest.sql

package pg

import (
	"context"

	"github.com/google/uuid"
)

const loadTestDelete = `-- name: LoadTestDelete :exec
delete from load_test
where id = $1
`

func (q *Queries) LoadTestDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, loadTestDelete, id)
	return err
}

const loadTestInsert = `-- name: LoadTestInsert :exec
insert into load_test(id, value)
values ( $1, $2)
`

type LoadTestInsertParams struct {
	ID    uuid.UUID
	Value string
}

func (q *Queries) LoadTestInsert(ctx context.Context, arg LoadTestInsertParams) error {
	_, err := q.db.Exec(ctx, loadTestInsert, arg.ID, arg.Value)
	return err
}
