// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pg

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	FriendCrete(ctx context.Context, arg FriendCreteParams) error
	FriendDelete(ctx context.Context, arg FriendDeleteParams) error
	FriendIDsByUserID(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	LastPostsByUserIDsWithOffsetLimit(ctx context.Context, arg LastPostsByUserIDsWithOffsetLimitParams) ([]Post, error)
	LoadTestDelete(ctx context.Context, id uuid.UUID) error
	LoadTestInsert(ctx context.Context, arg LoadTestInsertParams) error
	PostCreate(ctx context.Context, arg PostCreateParams) error
	PostDelete(ctx context.Context, id uuid.UUID) error
	PostGetByID(ctx context.Context, id uuid.UUID) (Post, error)
	PostGetWithLockByID(ctx context.Context, id uuid.UUID) (Post, error)
	PostUpdate(ctx context.Context, arg PostUpdateParams) error
	UserCreate(ctx context.Context, arg UserCreateParams) error
	UserGetByID(ctx context.Context, id uuid.UUID) (User, error)
	UsersGetByFirstNameSecondName(ctx context.Context, arg UsersGetByFirstNameSecondNameParams) ([]User, error)
	UsersMassCreate(ctx context.Context, arg []UsersMassCreateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
